### ISSUE TITLE
Large Desktop View

### ISSUE THREAD

**Issue by yejonlhee** [UBC-iGEM/ubc-igem.github.io#15]
LUCY. THERE'S A DOOKIE ON MY PART. look what happened when i tried looking at our beautiful website on my big monitor. 
![image](https://github.com/UBC-iGEM/ubc-igem.github.io/assets/151305749/458ed0d4-7cba-4abd-ad5d-ee22d9b74397)

this seems to be the problem for all of the footers for the pages :(( Let me know if you need any help with this. 

As well, under "about" the title of "The iGEM Jamboree" is like split off when you view it on the big monitor. 
![image](https://github.com/UBC-iGEM/ubc-igem.github.io/assets/151305749/443c4d88-8c65-4253-b8e4-4f123185085d)

but other than that - it's so beautiful. Thank you thank you thank you so much for all of your help!

**Comment by lhao03** [comment]
oh no 💀 , i will see to that

**Comment by lhao03** [comment]
![Peek 2024-01-16 13-42](https://github.com/UBC-iGEM/ubc-igem.github.io/assets/55033656/503c4e82-0a41-4b82-842d-cd9c61d6c354)

i dont think i can replicate the igem jamboree but i fixed the footer

**Comment by lhao03** [comment]
9af2d2d272bb1bfa52a2e4e7f9485010ccc9d0ee

**Comment by yejonlhee** [comment]
tahnk you :))
