### ISSUE TITLE
Member Photos

### ISSUE THREAD

**Issue by yejonlhee** [UBC-iGEM/ubc-igem.github.io#19]
Can we update the member photos on the our team subsection of the website? 

My vision is that we can place the member photos in the little round boxes, and when you hover over it with your cursor, it "fades" to the green box with the text describing their name and major? 

Before hover: 
<img width="453" alt="image" src="https://github.com/UBC-iGEM/ubc-igem.github.io/assets/151305749/579e572c-40e4-4d78-aa24-5733d916d431">

After hover: 
<img width="450" alt="image" src="https://github.com/UBC-iGEM/ubc-igem.github.io/assets/151305749/84129526-1cf1-4eb5-b422-d10107801e64">

Please feel free to ask questions if its unclear!

**Comment by lhao03** [comment]
i have completed the task lmk how it looks
